import { WordData } from './types';

export const UNIT_DATA: Record<number, WordData[]> = {
  1: [
    { id: '1_1', word: "feeling", definition: "感觉", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '1_2', word: "tired", definition: "疲惫的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '1_3', word: "sad", definition: "难过的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '1_4', word: "angry", definition: "生气的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '1_5', word: "scared", definition: "害怕的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '1_6', word: "cry", definition: "哭", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '1_7', word: "laugh", definition: "笑", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '1_8', word: "stamp", definition: "跺（脚）", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '1_9', word: "sleep", definition: "睡觉", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '1_10', word: "new", definition: "新的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '1_11', word: "game", definition: "游戏", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '1_12', word: "excited", definition: "兴奋的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '1_13', word: "sorry", definition: "对不起", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '1_14', word: "like", definition: "喜欢；像", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '1_15', word: "but", definition: "但是", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '1_16', word: "unhappy", definition: "不开心的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '1_17', word: "worried", definition: "担心的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '1_18', word: "not", definition: "不，不是", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '1_19', word: "lose", definition: "丢失", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '1_20', word: "doll", definition: "玩偶", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '1_21', word: "football", definition: "足球", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '1_22', word: "candy", definition: "糖果", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '1_23', word: "away", definition: "移走", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '1_24', word: "big", definition: "大的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '1_25', word: "mouse", definition: "老鼠", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '1_26', word: "talk about", definition: "讨论，谈论", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '1_27', word: "go to sleep", definition: "去睡觉", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '1_28', word: "happy birthday!", definition: "生日快乐！", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '1_29', word: "thank you.", definition: "谢谢。", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '1_30', word: "have/has got", definition: "有，拥有", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '1_31', word: "play the game", definition: "玩游戏", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '1_32', word: "play football", definition: "踢足球", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '1_33', word: "all day", definition: "整天", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '1_34', word: "take sb/sth away", definition: "带走······", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '1_35', word: "jump out", definition: "跳出来", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '1_36', word: "a big box of", definition: "一大盒的······", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '1_37', word: "find food", definition: "寻找食物", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '1_38', word: "such as", definition: "例如", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '1_39', word: "Toby's feelings", definition: "托比的感受", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '1_40', word: "Tutu is excited.", definition: "图图很兴奋。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '1_41', word: "I've got a game. Let's play!", definition: "我有个游戏。我们来玩吧！", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '1_42', word: "I don't like your new game.", definition: "我不喜欢你的新游戏。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '1_43', word: "Do you like the game? Yes,it's great!", definition: "你喜欢这个游戏吗？是的，太棒了！", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '1_44', word: "Let's play the game. OK! It's fun!", definition: "我们来玩游戏吧。好的！这很有趣！", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '1_45', word: "I'm sorry. Dad. That's OK, Tutu.", definition: "我很抱歉。爸爸。没关系，图图。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '1_46', word: "How is he/she feeling?", definition: "他/她感觉怎么样？", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '1_47', word: "He is angry/tired.", definition: "他很生气/累。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '1_48', word: "How are you feeling today?", definition: "你今天感觉怎么样？", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '1_49', word: "I'm happy.", definition: "我很高兴。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '1_50', word: "Li Ling loses her favourite doll. She is sad.", definition: "李玲失去了她最喜欢的玩偶。她很伤心。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '1_51', word: "Du Peng plays football all day. He is tired.", definition: "杜鹏整天踢足球。他累了。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '1_52', word: "A bird takes John's candy away. He is angry.", definition: "一只鸟拿走了约翰的糖果。他很生气。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '1_53', word: "A big mouse jumps out! Ann is scared.", definition: "一只大老鼠跳了出来！安很害怕。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
  ],
  2: [
    { id: '2_1', word: "from", definition: "从", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_2', word: "head", definition: "头", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_3', word: "toe", definition: "脚趾", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_4', word: "body", definition: "身体；躯干", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_5', word: "rock", definition: "摇滚乐", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_6', word: "song", definition: "歌曲", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_7', word: "touch", definition: "触摸", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_8', word: "eye", definition: "眼睛", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_9', word: "hair", definition: "头发", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_10', word: "ear", definition: "耳朵", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_11', word: "wave", definition: "摆动", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_12', word: "leg", definition: "腿", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_13', word: "foot", definition: "脚", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_14', word: "nose", definition: "鼻子", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_15', word: "face", definition: "脸", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_16', word: "arm", definition: "手臂", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_17', word: "hand", definition: "手", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_18', word: "mouth", definition: "嘴", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_19', word: "tooth", definition: "牙", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_20', word: "prize", definition: "奖品", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_21', word: "bike", definition: "自行车", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_22', word: "race", definition: "竞赛", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_23', word: "stretch", definition: "伸展", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_24', word: "shake", definition: "摇动", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_25', word: "here", definition: "在这里", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_26', word: "Mr", definition: "先生", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_27', word: "back", definition: "回到原处", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_28', word: "worry", definition: "担心", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_29', word: "tip", definition: "建议", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_30', word: "small", definition: "小的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_31', word: "robot", definition: "机器人", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_32', word: "his", definition: "他的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '2_33', word: "come on", definition: "快来", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '2_34', word: "sing a song", definition: "唱首歌", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '2_35', word: "touch your head", definition: "摸你的头", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '2_36', word: "touch your eyes", definition: "摸摸你的眼睛", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '2_37', word: "touch your hair", definition: "摸摸你的头发", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '2_38', word: "touch your ears", definition: "摸摸你的耳朵", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '2_39', word: "wave your legs", definition: "摆动你的腿", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '2_40', word: "touch your feet", definition: "摸摸你的脚", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '2_41', word: "touch your nose", definition: "摸摸你的鼻子", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '2_42', word: "touch your face", definition: "摸摸你的脸", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '2_43', word: "wave your arms", definition: "摆动你的胳膊", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '2_44', word: "wave your hands", definition: "摆动你的手", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '2_45', word: "open your mouth", definition: "张开你的嘴巴", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '2_46', word: "show your teeth", definition: "看看你的牙齿", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '2_47', word: "school bike race", definition: "学校自行车比赛", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '2_48', word: "stretch your arms", definition: "伸展你的胳膊", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '2_49', word: "stretch your legs", definition: "伸展你的腿", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '2_50', word: "shake your feet", definition: "晃动你的脚", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '2_51', word: "look at", definition: "看向·····", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '2_52', word: "first aid kit", definition: "急救包", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '2_53', word: "kick the ball", definition: "踢球", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '2_54', word: "It's time for the body rock.", definition: "是时候进行身体摇滚了。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '2_55', word: "Here's your prize", definition: "这是你的奖品", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '2_56', word: "Don't worry. I'm OK. Look at my prize!", definition: "别担心。我很好。看看我的奖品！", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '2_57', word: "That's a nice prize.", definition: "那是一个不错的奖品。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '2_58', word: "I've got big hands and feet.", definition: "我有一双大手和一双大脚。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '2_59', word: "He's got big ears.", definition: "他耳朵很大。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '2_60', word: "He hasn't got hair.", definition: "他没有头发。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '2_61', word: "This robot has got six hands.", definition: "这个机器人有六只手。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
  ],
  3: [
    { id: '3_1', word: "so", definition: "这么，如此", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_2', word: "cool", definition: "酷的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_3', word: "clothes", definition: "衣服", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_4', word: "wear", definition: "穿", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_5', word: "cap", definition: "帽子", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_6', word: "T-shirt", definition: "T恤", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_7', word: "trousers", definition: "裤子", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_8', word: "sock", definition: "袜子", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_9', word: "shiny", definition: "有光泽的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_10', word: "shoe", definition: "鞋", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_11', word: "dress", definition: "连衣裙", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_12', word: "sweater", definition: "毛线衣", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_13', word: "skirt", definition: "半身裙", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_14', word: "shirt", definition: "衬衫", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_15', word: "coat", definition: "外套", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_16', word: "shorts", definition: "短裤", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_17', word: "king", definition: "国王", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_18', word: "want", definition: "想要", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_19', word: "beautiful", definition: "美丽的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_20', word: "make", definition: "做", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_21', word: "magic", definition: "神奇的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_22', word: "clever", definition: "聪明的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_23', word: "them", definition: "它们", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_24', word: "month", definition: "一个月；月", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_25', word: "later", definition: "之后", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_26', word: "try", definition: "试", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_27', word: "why", definition: "为什么", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_28', word: "wonderful", definition: "令人惊叹的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_29', word: "most", definition: "最", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_30', word: "any", definition: "任何的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_31', word: "or", definition: "或", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_32', word: "fox", definition: "狐狸", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_33', word: "monkey", definition: "猴子", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_34', word: "tell", definition: "告诉；说出", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_35', word: "truth", definition: "真相", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_36', word: "wash", definition: "洗", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_37', word: "hang", definition: "悬挂", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_38', word: "hat", definition: "帽子", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_39', word: "jeans", definition: "牛仔裤", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_40', word: "boot", definition: "靴子", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_41', word: "robe", definition: "长袍", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '3_42', word: "be ready to go", definition: "准备好做去", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '3_43', word: "look cool", definition: "看起来很酷", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '3_44', word: "make clothes", definition: "做衣服", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '3_45', word: "tell the truth", definition: "讲出事实", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '3_46', word: "one month later", definition: "一个月后", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '3_47', word: "try them on", definition: "试穿一下", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '3_48', word: "come and see", definition: "快来看看", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '3_49', word: "Take out the clothes", definition: "把衣服拿出来", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '3_50', word: "Hang out the T-shirt", definition: "把T恤挂起来", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '3_51', word: "Look up", definition: "抬头看", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '3_52', word: "Hang out the Tousers.", definition: "把裤子挂起来。", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '3_53', word: "Take the clothes back in", definition: "把衣服拿回去", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '3_54', word: "Wash theclothes", definition: "洗衣服", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '3_55', word: "Hang out the shorts.", definition: "把短裤挂起来。", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '3_56', word: "Hang out the socks", definition: "把袜子挂起来", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '3_57', word: "look like", definition: "看起来像", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '3_58', word: "I look so cool today!", definition: "我今天看起来很酷！", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '3_59', word: "A white T-shirt on my back.", definition: "我背上有一件白色T恤。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '3_60', word: "And blue trousers on my legs.", definition: "我腿上穿着蓝色裤子。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '3_61', word: "I look cool for school today!", definition: "我今天上学看起来很酷", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '3_62', word: "The king wants beautiful clothes!", definition: "国王想要漂亮的衣服！", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '3_63', word: "We can make clothes for the king.", definition: "我们可以为国王做衣服。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '3_64', word: "Why can't I see the clothes?Am I not clever?", definition: "为什么我看不见衣服？我不聪明吗？", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '3_65', word: "What wonderful clothes!", definition: "多漂亮的衣服啊！", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '3_66', word: "The king is in his beautiful new clothes!", definition: "国王穿着漂亮的新衣服！", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '3_67', word: "But he isn't wearing any clothes!", definition: "但他没有穿任何衣服！", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '3_68', word: "The foxes can make magic clothes.", definition: "狐狸能制作有魔法的衣服。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '3_69', word: "The monkey tells the truth.", definition: "猴子说出真相。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '3_70', word: "Jerry is wearing a hat,a shirt,jeans and boots.", definition: "杰瑞戴着帽子、衬衫、牛仔裤和靴子。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '3_71', word: "Yang Xue is wearing a red hat,a black and red dress,and black shoes.", definition: "杨雪戴着一顶红帽子，穿着一件黑色和红色的裙子，还有一双黑色的鞋子。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '3_72', word: "The lake looks like a moon.", definition: "这个湖看起来像月亮。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '3_73', word: "Amonkey is drinking milk.", definition: "一只猴子正在喝牛奶。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
  ],
  4: [
    { id: '4_1', word: "rain", definition: "雨", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_2', word: "shine", definition: "光亮", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_3', word: "rainy", definition: "多雨的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_4', word: "run", definition: "跑", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_5', word: "windy", definition: "多风的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_6', word: "fly", definition: "放飞", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_7', word: "kite", definition: "风筝", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_8', word: "park", definition: "公园", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_9', word: "hot", definition: "炎热的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_10', word: "sunny", definition: "阳光充足的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_11', word: "swim", definition: "游泳", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_12', word: "water", definition: "水", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_13', word: "cold", definition: "寒冷的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_14', word: "snowy", definition: "多雪的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_15', word: "throw", definition: "投，扔", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_16', word: "snowball", definition: "雪球", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_17', word: "raincoat", definition: "雨衣", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_18', word: "umbrella", definition: "雨伞", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_19', word: "warm", definition: "保暖的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_20', word: "music", definition: "音乐", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_21', word: "weather", definition: "天气", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_22', word: "bookshop", definition: "书店", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_23', word: "wait", definition: "等", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_24', word: "wet", definition: "湿的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_25', word: "again", definition: "又", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_26', word: "dry", definition: "干燥的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_27', word: "sell", definition: "卖", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_28', word: "these", definition: "这些", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_29', word: "idea", definition: "主意", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_30', word: "club", definition: "俱乐部", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_31', word: "stay", definition: "停留", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_32', word: "stand", definition: "站立", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_33', word: "tree", definition: "树", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_34', word: "walk", definition: "走", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_35', word: "carefully", definition: "小心地", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_36', word: "spring", definition: "春天", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_37', word: "summer", definition: "夏天", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_38', word: "autumn", definition: "秋天", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_39', word: "winter", definition: "冬天", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_40', word: "season", definition: "季节", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_41', word: "step", definition: "步骤", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_42', word: "drawing", definition: "图画", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_43', word: "cloudy", definition: "多云的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '4_44', word: "swim in the water", definition: "在水里游泳", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '4_45', word: "fly kites", definition: "放风筝", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '4_46', word: "throw snowballs", definition: "扔雪球", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '4_47', word: "books for all weather", definition: "全气候图书", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '4_48', word: "take the books outside", definition: "把书带到户外", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '4_49', word: "the All Weather Book Club", definition: "全气候图书俱乐部", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '4_50', word: "the next day", definition: "第二天", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '4_51', word: "go out to play", definition: "去外面玩", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '4_52', word: "stay away from", definition: "远离", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '4_53', word: "Walk carefully!", definition: "小心走路!", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '4_54', word: "a book club", definition: "图书俱乐部", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '4_55', word: "read books", definition: "读书。", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '4_56', word: "draw a window.", definition: "画窗户。", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '4_57', word: "cut the window", definition: "剪窗户", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '4_58', word: "How do we play on a rainy,rainy day?", definition: "我们怎么玩 在一个阴雨天？", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '4_59', word: "We run and we jump on a rainy,rainy day!", definition: "我们跑，我们跳在一个阴雨天！", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '4_60', word: "I've got my raincoat and umbrella.", definition: "我有雨衣和雨伞", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '4_61', word: "It's rainy/windy/suny.", definition: "下雨/刮风/晴天。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '4_62', word: "What's the weather like?", definition: "天气怎么样？", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '4_63', word: "It's sunny and cool", definition: "天气晴朗，很凉爽", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '4_64', word: "Let's take the books outside.", definition: "我们把书拿到外面去吧。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '4_65', word: "Welcome to the All Weather Book Club!", definition: "欢迎来到全天候图书俱乐部！", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '4_66', word: "I don't want to play outside.", definition: "我不想在外面玩。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '4_67', word: "They read books in the club.", definition: "他们在俱乐部看书。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '4_68', word: "They wait in front of a bookshop", definition: "他们在书店前等着。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '4_69', word: "Stay away from the board!", definition: "远离广告牌", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '4_70', word: "Don't stand under the tree!", definition: "别站在树下！", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '4_71', word: "What's your favourite season?I like spring best.", definition: "你最喜欢的季节是什么？我最喜欢春天。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '4_72', word: "What's the weather like in spring? It's warm.", definition: "春天的天气怎么样？天气很暖和。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '4_73', word: "What do you do in spring? I fly a kite.", definition: "你在春天做什么？我放风筝。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '4_74', word: "What's the season? It's autumn.", definition: "什么季节？它是秋天。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
  ],
  5: [
    { id: '5_1', word: "week", definition: "星期", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '5_2', word: "Monday", definition: "星期一", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '5_3', word: "Tuesday", definition: "星期二", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '5_4', word: "Wednesday", definition: "星期三", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '5_5', word: "Thursday", definition: "星期四", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '5_6', word: "Friday", definition: "星期五", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '5_7', word: "Saturday", definition: "星期六", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '5_8', word: "Sunday", definition: "星期日", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '5_9', word: "before", definition: "在……以前", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '5_10', word: "after", definition: "在……后", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '5_11', word: "room", definition: "房间", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '5_12', word: "close", definition: "关，闭合", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '5_13', word: "much", definition: "非常", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '5_14', word: "rabbit", definition: "兔", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '5_15', word: "cat", definition: "猫", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '5_16', word: "fish", definition: "鱼", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '5_17', word: "busy", definition: "忙碌的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '5_18', word: "every", definition: "每一个", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '5_19', word: "cook", definition: "烹调", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '5_20', word: "study", definition: "学习", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '5_21', word: "basketball", definition: "篮球", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '5_22', word: "the day before", definition: "······的前一天", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '5_23', word: "the day after", definition: "······的后一天", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '5_24', word: "close your eyes", definition: "闭上你的眼睛", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '5_25', word: "open your eyes", definition: "睁开你的眼睛", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '5_26', word: "so much", definition: "太，很，非常", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '5_27', word: "paint pictures", definition: "画画", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '5_28', word: "on the wall", definition: "在墙上", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '5_29', word: "of course", definition: "当然", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '5_30', word: "WuShu Club", definition: "武术俱乐部", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '5_31', word: "Singing Club", definition: "唱歌俱乐部", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '5_32', word: "Cooking Club", definition: "烹饪俱乐部", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '5_33', word: "Chinese Chess Club", definition: "象棋俱乐部", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '5_34', word: "study English", definition: "学英语", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '5_35', word: "play basketball", definition: "打篮球", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '5_36', word: "clean my room", definition: "打扫房间", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '5_37', word: "wake up", definition: "醒醒，醒来", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '5_38', word: "visit the zoo", definition: "游览动物园", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '5_39', word: "go to the zoo", definition: "去动物园", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '5_40', word: "Days of the week", definition: "一周中的几天", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '5_41', word: "It's sunny on Monday.", definition: "星期一阳光明媚。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '5_42', word: "What day is it today? It's Friday.", definition: "今天星期几？今天是星期五。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '5_43', word: "How do you like your new room?", definition: "你喜欢你的新房间吗？", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '5_44', word: "I don't like pink so much now!", definition: "我现在不太喜欢粉红色了！", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '5_45', word: "Can I paint pictures on the wall?", definition: "我可以在墙上画画吗？", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '5_46', word: "Nana has got a busy week", definition: "娜娜有忙碌了一周", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '5_47', word: "She paints a red bird on Monday", definition: "她星期一画了一只红鸟", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '5_48', word: "Meet every Wednesday and do wushu.", definition: "每周三聚会，做武术。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '5_49', word: "Come to the club on Friday. Let's cook!", definition: "星期五来俱乐部。我们做饭吧！", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '5_50', word: "Let's meet on Monday. It's a great game!", definition: "我们星期一见吧。这是一场精彩的比赛！", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
  ],
  6: [
    { id: '6_1', word: "eat", definition: "吃", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_2', word: "apple", definition: "苹果", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_3', word: "egg", definition: "鸡蛋", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_4', word: "bread", definition: "面包", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_5', word: "milk", definition: "奶", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_6', word: "rice", definition: "米；米饭", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_7', word: "tomato", definition: "西红柿", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_8', word: "juice", definition: "果汁", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_9', word: "ice cream", definition: "冰激凌", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_10', word: "chicken", definition: "鸡肉", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_11', word: "noodle", definition: "面条", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_12', word: "banana", definition: "香蕉", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_13', word: "finish", definition: "结尾", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_14', word: "dinner", definition: "正餐", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_15', word: "welcome", definition: "欢迎", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_16', word: "parent", definition: "父，母", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_17', word: "dish", definition: "一道菜", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_18', word: "meat", definition: "肉", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_19', word: "really", definition: "真的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_20', word: "mushroom", definition: "蘑菇", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_21', word: "potato", definition: "土豆", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_22', word: "eggplant", definition: "茄子", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_23', word: "believe", definition: "相信", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_24', word: "Chinese", definition: "中国的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_25', word: "food", definition: "食物", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_26', word: "amazing", definition: "惊人的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_27', word: "say", definition: "说", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_28', word: "tummy", definition: "肚子", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_29', word: "yummy", definition: "很好吃的", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_30', word: "grape", definition: "葡萄", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_31', word: "vegetable", definition: "蔬菜", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_32', word: "soup", definition: "汤", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_33', word: "pizza", definition: "比萨饼", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_34', word: "drink", definition: "饮料", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_35', word: "dumpling", definition: "水饺", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_36', word: "need", definition: "需要", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_37', word: "wrapper", definition: "包装材料", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_38', word: "mix", definition: "（使）混合", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_39', word: "carrot", definition: "胡萝卜", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_40', word: "add", definition: "添加", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_41', word: "salt", definition: "盐", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_42', word: "oil", definition: "植物油，动物油", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_43', word: "minute", definition: "分，分钟", exampleSentence: "", partOfSpeech: 'word', correctCount: 0 },
    { id: '6_44', word: "come in", definition: "进来", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '6_45', word: "meet my parents", definition: "见见我的父母", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '6_46', word: "meat dish", definition: "肉菜", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '6_47', word: "Chinese food", definition: "中国菜", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '6_48', word: "come to", definition: "去到······", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '6_49', word: "say about", definition: "谈论", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '6_50', word: "vegetable soup", definition: "蔬菜汤", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '6_51', word: "make dumplings", definition: "做饺子", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '6_52', word: "dumpling wrappers", definition: "饺子皮", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '6_53', word: "cook the eggs", definition: "煮鸡蛋", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '6_54', word: "cut the carrots", definition: "切胡萝卜", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '6_55', word: "add oil and salt", definition: "加入盐和油", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '6_56', word: "put in", definition: "把······放进·····", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '6_57', word: "eat the dumplings", definition: "吃饺子", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '6_58', word: "mix the eggs and carrots", definition: "把鸡蛋和胡萝卜混合在一起。", exampleSentence: "", partOfSpeech: 'phrase', correctCount: 0 },
    { id: '6_59', word: "Li Feifei likes noodles and oranges.", definition: "李飞飞喜欢面条和桔子。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '6_60', word: "What's for dinner?", definition: "晚饭吃什么？", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '6_61', word: "Dinner is ready.", definition: "晚饭准备好了。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '6_62', word: "Do you like the dishes?", definition: "你喜欢这些菜吗？", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '6_63', word: "I like these meat dishes!", definition: "我喜欢这些肉菜！", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '6_64', word: "These are mushrooms and eggplants.", definition: "这些是蘑菇和茄子。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '6_65', word: "I cant believe it.", definition: "我简直不敢相信。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '6_66', word: "Chinese food is amazing!", definition: "中国菜太棒了！", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '6_67', word: "Who comes to Nana's home?", definition: "谁来娜娜家？", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '6_68', word: "What are the three dishes?", definition: "这三道菜是什么？", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '6_69', word: "What does Tom say about Chinese food?", definition: "汤姆怎么说中国菜？", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '6_70', word: "My favourite food is pizza and my favourite drink is milk.", definition: "我最喜欢的食物是披萨，最喜欢的饮料是牛奶 。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '6_71', word: "Put the eggs and carrots in the wrappers.", definition: "把鸡蛋和胡萝卜放在包装纸里。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
    { id: '6_72', word: "Cook the dumplings for about six minutes.", definition: "把饺子煮大约六分钟。", exampleSentence: "", partOfSpeech: 'sentence', correctCount: 0 },
  ],
};
