import { WordData } from './types';

export const UNIT_DATA: Record<number, WordData[]> = {
  1: [
    { id: '1_1', word: 'feeling', definition: '感觉', exampleSentence: "Toby's feelings", partOfSpeech: 'n', correctCount: 0 },
    { id: '1_2', word: 'tired', definition: '疲惫的', exampleSentence: "He is tired.", partOfSpeech: 'adj', correctCount: 0 },
    { id: '1_3', word: 'sad', definition: '难过的', exampleSentence: "She is sad.", partOfSpeech: 'adj', correctCount: 0 },
    { id: '1_4', word: 'angry', definition: '生气的', exampleSentence: "He is angry.", partOfSpeech: 'adj', correctCount: 0 },
    { id: '1_5', word: 'scared', definition: '害怕的', exampleSentence: "Ann is scared.", partOfSpeech: 'adj', correctCount: 0 },
    { id: '1_6', word: 'cry', definition: '哭', exampleSentence: "Don't cry.", partOfSpeech: 'v', correctCount: 0 },
    { id: '1_7', word: 'laugh', definition: '笑', exampleSentence: "They laugh.", partOfSpeech: 'v', correctCount: 0 },
    { id: '1_8', word: 'stamp', definition: '跺（脚）', exampleSentence: "Stamp your feet.", partOfSpeech: 'v', correctCount: 0 },
    { id: '1_9', word: 'sleep', definition: '睡觉', exampleSentence: "Go to sleep.", partOfSpeech: 'v', correctCount: 0 },
    { id: '1_10', word: 'new', definition: '新的', exampleSentence: "I don't like your new game.", partOfSpeech: 'adj', correctCount: 0 },
    { id: '1_11', word: 'game', definition: '游戏', exampleSentence: "Let's play the game.", partOfSpeech: 'n', correctCount: 0 },
    { id: '1_12', word: 'excited', definition: '兴奋的', exampleSentence: "Tutu is excited.", partOfSpeech: 'adj', correctCount: 0 },
    { id: '1_13', word: 'sorry', definition: '对不起', exampleSentence: "I'm sorry.", partOfSpeech: 'adj', correctCount: 0 },
    { id: '1_14', word: 'like', definition: '喜欢；像', exampleSentence: "Do you like the game?", partOfSpeech: 'v/prep', correctCount: 0 },
    { id: '1_15', word: 'but', definition: '但是', exampleSentence: "But I am happy.", partOfSpeech: 'conj', correctCount: 0 },
    { id: '1_16', word: 'unhappy', definition: '不开心的', exampleSentence: "He is unhappy.", partOfSpeech: 'adj', correctCount: 0 },
    { id: '1_17', word: 'worried', definition: '担心的', exampleSentence: "She is worried.", partOfSpeech: 'adj', correctCount: 0 },
    { id: '1_18', word: 'not', definition: '不，不是', exampleSentence: "I am not sad.", partOfSpeech: 'adv', correctCount: 0 },
    { id: '1_19', word: 'lose', definition: '丢失', exampleSentence: "Li Ling loses her favourite doll.", partOfSpeech: 'v', correctCount: 0 },
    { id: '1_20', word: 'doll', definition: '玩偶', exampleSentence: "This is a doll.", partOfSpeech: 'n', correctCount: 0 },
    { id: '1_21', word: 'football', definition: '足球', exampleSentence: "Du Peng plays football all day.", partOfSpeech: 'n', correctCount: 0 },
    { id: '1_22', word: 'candy', definition: '糖果', exampleSentence: "A bird takes John's candy away.", partOfSpeech: 'n', correctCount: 0 },
    { id: '1_23', word: 'away', definition: '移走', exampleSentence: "A bird takes John's candy away.", partOfSpeech: 'adv', correctCount: 0 },
    { id: '1_24', word: 'big', definition: '大的', exampleSentence: "A big mouse jumps out!", partOfSpeech: 'adj', correctCount: 0 },
    { id: '1_25', word: 'mouse', definition: '老鼠', exampleSentence: "A big mouse jumps out!", partOfSpeech: 'n', correctCount: 0 },
  ],
  2: [
    { id: '2_1', word: 'from', definition: '从', exampleSentence: "From head to toe.", partOfSpeech: 'prep', correctCount: 0 },
    { id: '2_2', word: 'head', definition: '头', exampleSentence: "Touch your head.", partOfSpeech: 'n', correctCount: 0 },
    { id: '2_3', word: 'toe', definition: '脚趾', exampleSentence: "From head to toe.", partOfSpeech: 'n', correctCount: 0 },
    { id: '2_4', word: 'body', definition: '身体；躯干', exampleSentence: "It's time for the body rock.", partOfSpeech: 'n', correctCount: 0 },
    { id: '2_5', word: 'rock', definition: '摇滚乐', exampleSentence: "It's time for the body rock.", partOfSpeech: 'n', correctCount: 0 },
    { id: '2_6', word: 'song', definition: '歌曲', exampleSentence: "Sing a song.", partOfSpeech: 'n', correctCount: 0 },
    { id: '2_7', word: 'touch', definition: '触摸', exampleSentence: "Touch your head.", partOfSpeech: 'v', correctCount: 0 },
    { id: '2_8', word: 'eye', definition: '眼睛', exampleSentence: "Touch your eyes.", partOfSpeech: 'n', correctCount: 0 },
    { id: '2_9', word: 'hair', definition: '头发', exampleSentence: "He hasn't got hair.", partOfSpeech: 'n', correctCount: 0 },
    { id: '2_10', word: 'ear', definition: '耳朵', exampleSentence: "He's got big ears.", partOfSpeech: 'n', correctCount: 0 },
    { id: '2_11', word: 'wave', definition: '摆动', exampleSentence: "Wave your arms.", partOfSpeech: 'v', correctCount: 0 },
    { id: '2_12', word: 'leg', definition: '腿', exampleSentence: "Stretch your legs.", partOfSpeech: 'n', correctCount: 0 },
    { id: '2_13', word: 'foot', definition: '脚', exampleSentence: "I've got big hands and feet.", partOfSpeech: 'n', correctCount: 0 },
    { id: '2_14', word: 'nose', definition: '鼻子', exampleSentence: "Touch your nose.", partOfSpeech: 'n', correctCount: 0 },
    { id: '2_15', word: 'face', definition: '脸', exampleSentence: "Touch your face.", partOfSpeech: 'n', correctCount: 0 },
    { id: '2_16', word: 'arm', definition: '手臂', exampleSentence: "Stretch your arms.", partOfSpeech: 'n', correctCount: 0 },
    { id: '2_17', word: 'hand', definition: '手', exampleSentence: "I've got big hands and feet.", partOfSpeech: 'n', correctCount: 0 },
    { id: '2_18', word: 'mouth', definition: '嘴', exampleSentence: "Open your mouth.", partOfSpeech: 'n', correctCount: 0 },
    { id: '2_19', word: 'tooth', definition: '牙', exampleSentence: "Show your teeth.", partOfSpeech: 'n', correctCount: 0 },
    { id: '2_20', word: 'prize', definition: '奖品', exampleSentence: "Here's your prize.", partOfSpeech: 'n', correctCount: 0 },
    { id: '2_21', word: 'bike', definition: '自行车', exampleSentence: "School bike race.", partOfSpeech: 'n', correctCount: 0 },
    { id: '2_22', word: 'race', definition: '竞赛', exampleSentence: "School bike race.", partOfSpeech: 'n', correctCount: 0 },
    { id: '2_23', word: 'stretch', definition: '伸展', exampleSentence: "Stretch your arms.", partOfSpeech: 'v', correctCount: 0 },
    { id: '2_24', word: 'shake', definition: '摇动', exampleSentence: "Shake your feet.", partOfSpeech: 'v', correctCount: 0 },
    { id: '2_25', word: 'here', definition: '在这里', exampleSentence: "Here's your prize.", partOfSpeech: 'adv', correctCount: 0 },
    { id: '2_26', word: 'Mr', definition: '先生', exampleSentence: "Mr. Smith.", partOfSpeech: 'n', correctCount: 0 },
    { id: '2_27', word: 'back', definition: '回到原处', exampleSentence: "Go back.", partOfSpeech: 'adv', correctCount: 0 },
    { id: '2_28', word: 'worry', definition: '担心', exampleSentence: "Don't worry.", partOfSpeech: 'v', correctCount: 0 },
    { id: '2_29', word: 'tip', definition: '建议', exampleSentence: "A good tip.", partOfSpeech: 'n', correctCount: 0 },
    { id: '2_30', word: 'small', definition: '小的', exampleSentence: "A small robot.", partOfSpeech: 'adj', correctCount: 0 },
    { id: '2_31', word: 'robot', definition: '机器人', exampleSentence: "This robot has got six hands.", partOfSpeech: 'n', correctCount: 0 },
    { id: '2_32', word: 'his', definition: '他的', exampleSentence: "His hair.", partOfSpeech: 'pron', correctCount: 0 },
  ],
  3: [
    { id: '3_1', word: 'so', definition: '这么，如此', exampleSentence: "I look so cool today!", partOfSpeech: 'adv', correctCount: 0 },
    { id: '3_2', word: 'cool', definition: '酷的', exampleSentence: "I look so cool today!", partOfSpeech: 'adj', correctCount: 0 },
    { id: '3_3', word: 'clothes', definition: '衣服', exampleSentence: "The king wants beautiful clothes!", partOfSpeech: 'n', correctCount: 0 },
    { id: '3_4', word: 'wear', definition: '穿', exampleSentence: "Jerry is wearing a hat.", partOfSpeech: 'v', correctCount: 0 },
    { id: '3_5', word: 'cap', definition: '帽子', exampleSentence: "A red cap.", partOfSpeech: 'n', correctCount: 0 },
    { id: '3_6', word: 'T-shirt', definition: 'T恤', exampleSentence: "A white T-shirt on my back.", partOfSpeech: 'n', correctCount: 0 },
    { id: '3_7', word: 'trousers', definition: '裤子', exampleSentence: "And blue trousers on my legs.", partOfSpeech: 'n', correctCount: 0 },
    { id: '3_8', word: 'sock', definition: '袜子', exampleSentence: "Hang out the socks.", partOfSpeech: 'n', correctCount: 0 },
    { id: '3_9', word: 'shiny', definition: '有光泽的', exampleSentence: "Shiny shoes.", partOfSpeech: 'adj', correctCount: 0 },
    { id: '3_10', word: 'shoe', definition: '鞋', exampleSentence: "Black shoes.", partOfSpeech: 'n', correctCount: 0 },
    { id: '3_11', word: 'dress', definition: '连衣裙', exampleSentence: "A black and red dress.", partOfSpeech: 'n', correctCount: 0 },
    { id: '3_12', word: 'sweater', definition: '毛线衣', exampleSentence: "A warm sweater.", partOfSpeech: 'n', correctCount: 0 },
    { id: '3_13', word: 'skirt', definition: '半身裙', exampleSentence: "A blue skirt.", partOfSpeech: 'n', correctCount: 0 },
    { id: '3_14', word: 'shirt', definition: '衬衫', exampleSentence: "Jerry is wearing a shirt.", partOfSpeech: 'n', correctCount: 0 },
    { id: '3_15', word: 'coat', definition: '外套', exampleSentence: "A long coat.", partOfSpeech: 'n', correctCount: 0 },
    { id: '3_16', word: 'shorts', definition: '短裤', exampleSentence: "Hang out the shorts.", partOfSpeech: 'n', correctCount: 0 },
    { id: '3_17', word: 'king', definition: '国王', exampleSentence: "The king wants beautiful clothes!", partOfSpeech: 'n', correctCount: 0 },
    { id: '3_18', word: 'want', definition: '想要', exampleSentence: "The king wants beautiful clothes!", partOfSpeech: 'v', correctCount: 0 },
    { id: '3_19', word: 'beautiful', definition: '美丽的', exampleSentence: "What beautiful clothes!", partOfSpeech: 'adj', correctCount: 0 },
    { id: '3_20', word: 'make', definition: '做', exampleSentence: "We can make clothes for the king.", partOfSpeech: 'v', correctCount: 0 },
    { id: '3_21', word: 'magic', definition: '神奇的', exampleSentence: "The foxes can make magic clothes.", partOfSpeech: 'adj', correctCount: 0 },
    { id: '3_22', word: 'clever', definition: '聪明的', exampleSentence: "Am I not clever?", partOfSpeech: 'adj', correctCount: 0 },
    { id: '3_23', word: 'them', definition: '它们', exampleSentence: "Try them on.", partOfSpeech: 'pron', correctCount: 0 },
    { id: '3_24', word: 'month', definition: '一个月；月', exampleSentence: "One month later.", partOfSpeech: 'n', correctCount: 0 },
    { id: '3_25', word: 'later', definition: '之后', exampleSentence: "One month later.", partOfSpeech: 'adv', correctCount: 0 },
    { id: '3_26', word: 'try', definition: '试', exampleSentence: "Try them on.", partOfSpeech: 'v', correctCount: 0 },
    { id: '3_27', word: 'why', definition: '为什么', exampleSentence: "Why can't I see the clothes?", partOfSpeech: 'adv', correctCount: 0 },
    { id: '3_28', word: 'wonderful', definition: '令人惊叹的', exampleSentence: "What wonderful clothes!", partOfSpeech: 'adj', correctCount: 0 },
    { id: '3_29', word: 'most', definition: '最', exampleSentence: "The most beautiful clothes.", partOfSpeech: 'adv', correctCount: 0 },
    { id: '3_30', word: 'any', definition: '任何的', exampleSentence: "He isn't wearing any clothes!", partOfSpeech: 'adj', correctCount: 0 },
    { id: '3_31', word: 'or', definition: '或', exampleSentence: "Red or blue.", partOfSpeech: 'conj', correctCount: 0 },
    { id: '3_32', word: 'fox', definition: '狐狸', exampleSentence: "The foxes can make magic clothes.", partOfSpeech: 'n', correctCount: 0 },
    { id: '3_33', word: 'monkey', definition: '猴子', exampleSentence: "The monkey tells the truth.", partOfSpeech: 'n', correctCount: 0 },
    { id: '3_34', word: 'tell', definition: '告诉；说出', exampleSentence: "The monkey tells the truth.", partOfSpeech: 'v', correctCount: 0 },
    { id: '3_35', word: 'truth', definition: '真相', exampleSentence: "The monkey tells the truth.", partOfSpeech: 'n', correctCount: 0 },
    { id: '3_36', word: 'wash', definition: '洗', exampleSentence: "Wash the clothes.", partOfSpeech: 'v', correctCount: 0 },
    { id: '3_37', word: 'hang', definition: '悬挂', exampleSentence: "Hang out the T-shirt.", partOfSpeech: 'v', correctCount: 0 },
    { id: '3_38', word: 'hat', definition: '帽子', exampleSentence: "Jerry is wearing a hat.", partOfSpeech: 'n', correctCount: 0 },
    { id: '3_39', word: 'jeans', definition: '牛仔裤', exampleSentence: "Jerry is wearing jeans.", partOfSpeech: 'n', correctCount: 0 },
    { id: '3_40', word: 'boot', definition: '靴子', exampleSentence: "Jerry is wearing boots.", partOfSpeech: 'n', correctCount: 0 },
    { id: '3_41', word: 'robe', definition: '长袍', exampleSentence: "A magic robe.", partOfSpeech: 'n', correctCount: 0 },
  ],
  4: [
    { id: '4_1', word: 'rain', definition: '雨', exampleSentence: "Rain or shine.", partOfSpeech: 'n', correctCount: 0 },
    { id: '4_2', word: 'shine', definition: '光亮', exampleSentence: "Rain or shine.", partOfSpeech: 'n', correctCount: 0 },
    { id: '4_3', word: 'rainy', definition: '多雨的', exampleSentence: "How do we play on a rainy day?", partOfSpeech: 'adj', correctCount: 0 },
    { id: '4_4', word: 'run', definition: '跑', exampleSentence: "We run and we jump.", partOfSpeech: 'v', correctCount: 0 },
    { id: '4_5', word: 'windy', definition: '多风的', exampleSentence: "It's windy.", partOfSpeech: 'adj', correctCount: 0 },
    { id: '4_6', word: 'fly', definition: '放飞', exampleSentence: "I fly a kite.", partOfSpeech: 'v', correctCount: 0 },
    { id: '4_7', word: 'kite', definition: '风筝', exampleSentence: "I fly a kite.", partOfSpeech: 'n', correctCount: 0 },
    { id: '4_8', word: 'park', definition: '公园', exampleSentence: "Play in the park.", partOfSpeech: 'n', correctCount: 0 },
    { id: '4_9', word: 'hot', definition: '炎热的', exampleSentence: "It's hot.", partOfSpeech: 'adj', correctCount: 0 },
    { id: '4_10', word: 'sunny', definition: '阳光充足的', exampleSentence: "It's sunny and cool.", partOfSpeech: 'adj', correctCount: 0 },
    { id: '4_11', word: 'swim', definition: '游泳', exampleSentence: "Swim in the water.", partOfSpeech: 'v', correctCount: 0 },
    { id: '4_12', word: 'water', definition: '水', exampleSentence: "Swim in the water.", partOfSpeech: 'n', correctCount: 0 },
    { id: '4_13', word: 'cold', definition: '寒冷的', exampleSentence: "It's cold.", partOfSpeech: 'adj', correctCount: 0 },
    { id: '4_14', word: 'snowy', definition: '多雪的', exampleSentence: "It's snowy.", partOfSpeech: 'adj', correctCount: 0 },
    { id: '4_15', word: 'throw', definition: '投，扔', exampleSentence: "Throw snowballs.", partOfSpeech: 'v', correctCount: 0 },
    { id: '4_16', word: 'snowball', definition: '雪球', exampleSentence: "Throw snowballs.", partOfSpeech: 'n', correctCount: 0 },
    { id: '4_17', word: 'raincoat', definition: '雨衣', exampleSentence: "I've got my raincoat and umbrella.", partOfSpeech: 'n', correctCount: 0 },
    { id: '4_18', word: 'umbrella', definition: '雨伞', exampleSentence: "I've got my raincoat and umbrella.", partOfSpeech: 'n', correctCount: 0 },
    { id: '4_19', word: 'warm', definition: '保暖的', exampleSentence: "It's warm.", partOfSpeech: 'adj', correctCount: 0 },
    { id: '4_20', word: 'music', definition: '音乐', exampleSentence: "Listen to music.", partOfSpeech: 'n', correctCount: 0 },
    { id: '4_21', word: 'weather', definition: '天气', exampleSentence: "What's the weather like?", partOfSpeech: 'n', correctCount: 0 },
    { id: '4_22', word: 'bookshop', definition: '书店', exampleSentence: "They wait in front of a bookshop.", partOfSpeech: 'n', correctCount: 0 },
    { id: '4_23', word: 'wait', definition: '等', exampleSentence: "They wait in front of a bookshop.", partOfSpeech: 'v', correctCount: 0 },
    { id: '4_24', word: 'wet', definition: '湿的', exampleSentence: "It's wet.", partOfSpeech: 'adj', correctCount: 0 },
    { id: '4_25', word: 'again', definition: '又', exampleSentence: "Play again.", partOfSpeech: 'adv', correctCount: 0 },
    { id: '4_26', word: 'dry', definition: '干燥的', exampleSentence: "It's dry.", partOfSpeech: 'adj', correctCount: 0 },
    { id: '4_27', word: 'sell', definition: '卖', exampleSentence: "Sell books.", partOfSpeech: 'v', correctCount: 0 },
    { id: '4_28', word: 'these', definition: '这些', exampleSentence: "These books.", partOfSpeech: 'pron', correctCount: 0 },
    { id: '4_29', word: 'idea', definition: '主意', exampleSentence: "A good idea.", partOfSpeech: 'n', correctCount: 0 },
    { id: '4_30', word: 'club', definition: '俱乐部', exampleSentence: "Welcome to the All Weather Book Club!", partOfSpeech: 'n', correctCount: 0 },
    { id: '4_31', word: 'stay', definition: '停留', exampleSentence: "Stay away from the board!", partOfSpeech: 'v', correctCount: 0 },
    { id: '4_32', word: 'stand', definition: '站立', exampleSentence: "Don't stand under the tree!", partOfSpeech: 'v', correctCount: 0 },
    { id: '4_33', word: 'tree', definition: '树', exampleSentence: "Don't stand under the tree!", partOfSpeech: 'n', correctCount: 0 },
    { id: '4_34', word: 'walk', definition: '走', exampleSentence: "Walk carefully!", partOfSpeech: 'v', correctCount: 0 },
    { id: '4_35', word: 'carefully', definition: '小心地', exampleSentence: "Walk carefully!", partOfSpeech: 'adv', correctCount: 0 },
    { id: '4_36', word: 'spring', definition: '春天', exampleSentence: "I like spring best.", partOfSpeech: 'n', correctCount: 0 },
    { id: '4_37', word: 'summer', definition: '夏天', exampleSentence: "Summer is hot.", partOfSpeech: 'n', correctCount: 0 },
    { id: '4_38', word: 'autumn', definition: '秋天', exampleSentence: "It's autumn.", partOfSpeech: 'n', correctCount: 0 },
    { id: '4_39', word: 'winter', definition: '冬天', exampleSentence: "Winter is cold.", partOfSpeech: 'n', correctCount: 0 },
    { id: '4_40', word: 'season', definition: '季节', exampleSentence: "What's your favourite season?", partOfSpeech: 'n', correctCount: 0 },
    { id: '4_41', word: 'step', definition: '步骤', exampleSentence: "Next step.", partOfSpeech: 'n', correctCount: 0 },
    { id: '4_42', word: 'drawing', definition: '图画', exampleSentence: "A drawing.", partOfSpeech: 'n', correctCount: 0 },
    { id: '4_43', word: 'cloudy', definition: '多云的', exampleSentence: "It's cloudy.", partOfSpeech: 'adj', correctCount: 0 },
  ],
  5: [
    { id: '5_1', word: 'week', definition: '星期', exampleSentence: "Days of the week.", partOfSpeech: 'n', correctCount: 0 },
    { id: '5_2', word: 'Monday', definition: '星期一', exampleSentence: "It's sunny on Monday.", partOfSpeech: 'n', correctCount: 0 },
    { id: '5_3', word: 'Tuesday', definition: '星期二', exampleSentence: "Tuesday is fine.", partOfSpeech: 'n', correctCount: 0 },
    { id: '5_4', word: 'Wednesday', definition: '星期三', exampleSentence: "Meet every Wednesday.", partOfSpeech: 'n', correctCount: 0 },
    { id: '5_5', word: 'Thursday', definition: '星期四', exampleSentence: "Thursday is good.", partOfSpeech: 'n', correctCount: 0 },
    { id: '5_6', word: 'Friday', definition: '星期五', exampleSentence: "Come to the club on Friday.", partOfSpeech: 'n', correctCount: 0 },
    { id: '5_7', word: 'Saturday', definition: '星期六', exampleSentence: "Saturday is fun.", partOfSpeech: 'n', correctCount: 0 },
    { id: '5_8', word: 'Sunday', definition: '星期日', exampleSentence: "Sunday is relaxing.", partOfSpeech: 'n', correctCount: 0 },
    { id: '5_9', word: 'before', definition: '在……以前', exampleSentence: "The day before.", partOfSpeech: 'prep', correctCount: 0 },
    { id: '5_10', word: 'after', definition: '在……后', exampleSentence: "The day after.", partOfSpeech: 'prep', correctCount: 0 },
    { id: '5_11', word: 'room', definition: '房间', exampleSentence: "How do you like your new room?", partOfSpeech: 'n', correctCount: 0 },
    { id: '5_12', word: 'close', definition: '关，闭合', exampleSentence: "Close your eyes.", partOfSpeech: 'v', correctCount: 0 },
    { id: '5_13', word: 'much', definition: '非常', exampleSentence: "I don't like pink so much now!", partOfSpeech: 'adv', correctCount: 0 },
    { id: '5_14', word: 'rabbit', definition: '兔', exampleSentence: "A white rabbit.", partOfSpeech: 'n', correctCount: 0 },
    { id: '5_15', word: 'cat', definition: '猫', exampleSentence: "A cute cat.", partOfSpeech: 'n', correctCount: 0 },
    { id: '5_16', word: 'fish', definition: '鱼', exampleSentence: "A small fish.", partOfSpeech: 'n', correctCount: 0 },
    { id: '5_17', word: 'busy', definition: '忙碌的', exampleSentence: "Nana has got a busy week.", partOfSpeech: 'adj', correctCount: 0 },
    { id: '5_18', word: 'every', definition: '每一个', exampleSentence: "Meet every Wednesday.", partOfSpeech: 'adj', correctCount: 0 },
    { id: '5_19', word: 'cook', definition: '烹调', exampleSentence: "Let's cook!", partOfSpeech: 'v', correctCount: 0 },
    { id: '5_20', word: 'study', definition: '学习', exampleSentence: "Study English.", partOfSpeech: 'v', correctCount: 0 },
    { id: '5_21', word: 'basketball', definition: '篮球', exampleSentence: "Play basketball.", partOfSpeech: 'n', correctCount: 0 },
  ],
  6: [
    { id: '6_1', word: 'eat', definition: '吃', exampleSentence: "Time to eat.", partOfSpeech: 'v', correctCount: 0 },
    { id: '6_2', word: 'apple', definition: '苹果', exampleSentence: "An apple.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_3', word: 'egg', definition: '鸡蛋', exampleSentence: "Cook the eggs.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_4', word: 'bread', definition: '面包', exampleSentence: "Some bread.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_5', word: 'milk', definition: '奶', exampleSentence: "My favourite drink is milk.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_6', word: 'rice', definition: '米；米饭', exampleSentence: "Some rice.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_7', word: 'tomato', definition: '西红柿', exampleSentence: "A red tomato.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_8', word: 'juice', definition: '果汁', exampleSentence: "Some juice.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_9', word: 'ice cream', definition: '冰激凌', exampleSentence: "I like ice cream.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_10', word: 'chicken', definition: '鸡肉', exampleSentence: "Some chicken.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_11', word: 'noodle', definition: '面条', exampleSentence: "Li Feifei likes noodles.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_12', word: 'banana', definition: '香蕉', exampleSentence: "A yellow banana.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_13', word: 'finish', definition: '结尾', exampleSentence: "Finish your dinner.", partOfSpeech: 'v', correctCount: 0 },
    { id: '6_14', word: 'dinner', definition: '正餐', exampleSentence: "What's for dinner?", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_15', word: 'welcome', definition: '欢迎', exampleSentence: "Welcome to my home.", partOfSpeech: 'v', correctCount: 0 },
    { id: '6_16', word: 'parent', definition: '父，母', exampleSentence: "Meet my parents.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_17', word: 'dish', definition: '一道菜', exampleSentence: "Do you like the dishes?", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_18', word: 'meat', definition: '肉', exampleSentence: "I like these meat dishes!", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_19', word: 'really', definition: '真的', exampleSentence: "It's really good.", partOfSpeech: 'adv', correctCount: 0 },
    { id: '6_20', word: 'mushroom', definition: '蘑菇', exampleSentence: "These are mushrooms.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_21', word: 'potato', definition: '土豆', exampleSentence: "A potato.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_22', word: 'eggplant', definition: '茄子', exampleSentence: "These are eggplants.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_23', word: 'believe', definition: '相信', exampleSentence: "I can't believe it.", partOfSpeech: 'v', correctCount: 0 },
    { id: '6_24', word: 'Chinese', definition: '中国的', exampleSentence: "Chinese food is amazing!", partOfSpeech: 'adj', correctCount: 0 },
    { id: '6_25', word: 'food', definition: '食物', exampleSentence: "Chinese food is amazing!", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_26', word: 'amazing', definition: '惊人的', exampleSentence: "Chinese food is amazing!", partOfSpeech: 'adj', correctCount: 0 },
    { id: '6_27', word: 'say', definition: '说', exampleSentence: "What does Tom say?", partOfSpeech: 'v', correctCount: 0 },
    { id: '6_28', word: 'tummy', definition: '肚子', exampleSentence: "My tummy is full.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_29', word: 'yummy', definition: '很好吃的', exampleSentence: "It's yummy.", partOfSpeech: 'adj', correctCount: 0 },
    { id: '6_30', word: 'grape', definition: '葡萄', exampleSentence: "A grape.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_31', word: 'vegetable', definition: '蔬菜', exampleSentence: "Vegetable soup.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_32', word: 'soup', definition: '汤', exampleSentence: "Vegetable soup.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_33', word: 'pizza', definition: '比萨饼', exampleSentence: "My favourite food is pizza.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_34', word: 'drink', definition: '饮料', exampleSentence: "My favourite drink is milk.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_35', word: 'dumpling', definition: '水饺', exampleSentence: "Make dumplings.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_36', word: 'need', definition: '需要', exampleSentence: "I need some water.", partOfSpeech: 'v', correctCount: 0 },
    { id: '6_37', word: 'wrapper', definition: '包装材料', exampleSentence: "Dumpling wrappers.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_38', word: 'mix', definition: '（使）混合', exampleSentence: "Mix the eggs and carrots.", partOfSpeech: 'v', correctCount: 0 },
    { id: '6_39', word: 'carrot', definition: '胡萝卜', exampleSentence: "Cut the carrots.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_40', word: 'add', definition: '添加', exampleSentence: "Add oil and salt.", partOfSpeech: 'v', correctCount: 0 },
    { id: '6_41', word: 'salt', definition: '盐', exampleSentence: "Add oil and salt.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_42', word: 'oil', definition: '植物油，动物油', exampleSentence: "Add oil and salt.", partOfSpeech: 'n', correctCount: 0 },
    { id: '6_43', word: 'minute', definition: '分，分钟', exampleSentence: "Cook for six minutes.", partOfSpeech: 'n', correctCount: 0 },
  ]
};
